Import('env')
if env['ARCH'] == 'gem5':
    env.M3Program(env, 'accelchain', ['direct.cc', 'indirect.cc', 'accelchain.cc'])
    if False:
        env.M3Program(env, 'fft1d', env.Glob('fft1d.cc'))
        env.M3Program(env, 'swfilter', env.Glob('swfilter.cc'))
