import os

Import('env')
env.InstallFiles('$FSDIR/default', '.', scan=1)

env.M3Strip('$FSDIR/default/bin/bench-syscall', '$BINARYDIR/bench-syscall')
env.M3Strip('$FSDIR/default/bin/cat', '$BINARYDIR/cat')
env.M3Strip('$FSDIR/default/bin/cp', '$BINARYDIR/cp')
env.M3Strip('$FSDIR/default/bin/echo', '$BINARYDIR/echo')
env.M3Strip('$FSDIR/default/bin/filterchain', '$BINARYDIR/filterchain')
env.M3Strip('$FSDIR/default/bin/fstest', '$BINARYDIR/fstest')
env.M3Strip('$FSDIR/default/bin/hello', '$BINARYDIR/hello')
env.M3Strip('$FSDIR/default/bin/init', '$BINARYDIR/init')
if env['ARCH'] != 'host':
    env.M3Strip('$FSDIR/default/bin/idle', '$BINARYDIR/idle')
env.M3Strip('$FSDIR/default/bin/ls', '$BINARYDIR/ls')
env.M3Strip('$FSDIR/default/bin/noop', '$BINARYDIR/noop')
env.M3Strip('$FSDIR/default/bin/parchksum', '$BINARYDIR/parchksum')
if env['ARCH'] == 'gem5':
    env.M3Strip('$FSDIR/default/bin/pgchild', '$BINARYDIR/pgchild')
env.M3Strip('$FSDIR/default/bin/pipe', '$BINARYDIR/pipe')
env.M3Strip('$FSDIR/default/bin/rdwr', '$BINARYDIR/rdwr')
env.M3Strip('$FSDIR/default/bin/readelf', '$BINARYDIR/readelf')
if env['ARCH'] == 't2':
    env.M3Strip('$FSDIR/default/bin/sendfile', '$BINARYDIR/sendfile')
env.M3Strip('$FSDIR/default/bin/shell', '$BINARYDIR/shell')
env.M3Strip('$FSDIR/default/bin/unittests', '$BINARYDIR/unittests')
if env['ARCH'] == 'host':
    env.M3Strip('$FSDIR/default/bin/unittests-dtu', '$BINARYDIR/unittests-dtu')
env.M3Strip('$FSDIR/default/bin/unittests-fs', '$BINARYDIR/unittests-fs')
env.M3Strip('$FSDIR/default/bin/unittests-misc', '$BINARYDIR/unittests-misc')
env.M3Strip('$FSDIR/default/bin/unittests-stream', '$BINARYDIR/unittests-stream')
env.M3Strip('$FSDIR/default/bin/wc', '$BINARYDIR/wc')

bpe = 0 if os.environ.get('M3_FSBPE') is None else int(os.environ.get('M3_FSBPE'))
if os.environ.get('M3_FSBLKS') is None:
    if env['ARCH'] == 't2' or env['ARCH'] == 't3':
        blocks = 16384
    else:
        blocks = 4096
else:
    blocks = int(os.environ.get('M3_FSBLKS'))
env.M3Mkfs(target = 'default.img', source = '$FSDIR/default', blocks = blocks, inodes = 256, blks_per_ext = bpe)

args = '--sim' if env['ARCH'] == 't3' else ''
env.M3FileDump(target = 'default.img.mem', source = 'default.img', addr = 0x1000000, args = args)
