import os

Import('env')
env.InstallFiles('$FSDIR/default', '.', scan=1)

for f in env.Glob('$BINARYDIR/*'):
    if not f.abspath.endswith('kernel') and not f.abspath.endswith('.a'):
        env.M3Strip('$FSDIR/default/bin/${SOURCE.file}', f)

bpe = 0 if os.environ.get('M3_FSBPE') is None else int(os.environ.get('M3_FSBPE'))
if os.environ.get('M3_FSBLKS') is None:
    if env['ARCH'] == 't2' or env['ARCH'] == 't3':
        blocks = 16384
    else:
        blocks = 8192
else:
    blocks = int(os.environ.get('M3_FSBLKS'))
env.M3Mkfs(target = 'default.img', source = '$FSDIR/default', blocks = blocks, inodes = 256, blks_per_ext = bpe)

if env['ARCH'] in ['t2', 't3']:
    args = '--sim' if env['ARCH'] == 't3' else ''
    env.M3FileDump(target = 'default.img.mem', source = 'default.img', addr = 0x1000000, args = args)
