// This file has been automatically generated by strace2c.
// Do not edit it!

#include "../common/op_types.h"

trace_op_t trace_ops_cat_awk_cat[] = {
    /* #1 = 0x1 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 61966 } },
    /* #2 = 0x2 */ { .opcode = OPEN_OP, .args.open = { 3, "/pipedata/1024k.txt", O_RDONLY, 0 } },
    /* #3 = 0x3 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 3556 } },
    /* #4 = 0x4 */ { .opcode = SENDFILE_OP, .args.sendfile = { 1048576, 1, 3, 0, 16777216 } },
    /* #5 = 0x5 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 2679 } },
    /* #6 = 0x6 */ { .opcode = SENDFILE_OP, .args.sendfile = { 0, 1, 3, 0, 16777216 } },
    /* #7 = 0x7 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 8505 } },
    /* #8 = 0x8 */ { .opcode = CLOSE_OP, .args.close = { 0, 3 } },
    { .opcode = INVALID_OP } 
};
