Import('env', 'hostenv')

# apps that run everywhere
dirs = [
    'arithserv', 'hello', 'clisrv', 'kernel', 'rdwr', 'unittests', 'shell', 'echo', 'cat',
    'm3fs', 'fstest', 'init', 'readelf', 'parchksum', 'filterchain', 'noop',
    'float', 'srvtest', 'bench', 'pipe', 'execpipe', 'ls', 'fstrace'
]

# architecture / machine specific apps
if env['ARCH'] == 't2':
    dirs += ['profiler', 'profiler_cm', 'idle', 'sendfile', 'hello-cm']
elif env['ARCH'] == 't3':
    dirs += ['idle']
elif env['ARCH'] == 'host':
    dirs += [
        'asciiplay', 'intserver', 'keyb', 'plasma',
        'queue', 'stream', 'timer', 'vga'
    ]
elif env['ARCH'] == 'gem5':
    dirs += ['idle']

for d in dirs:
    env.SConscript(env.Glob(d + '/SConscript'), exports = ['env', 'hostenv'])
