Import('env')

myenv = env.Clone()
archtype = 'th' if myenv['ARCH'] == 't2' or myenv['ARCH'] == 't3' else ''
myenv.M3Program(
    myenv,
    target = 'kernel',
    source = [
        myenv.Glob('*.cc'),
        myenv.Glob('arch/$ARCH/*.cc'),
        myenv.Glob('arch/' + archtype + '/*.cc'),
        myenv.Glob('arch/$ARCH/*/*.cc')
    ],
    libs = ['X11', 'rt'] if myenv['ARCH'] == 'host' else []
)
