Import('env')

myenv = env.Clone()
myenv.M3Program(
    myenv,
    target = 'kernel',
    source = [
        myenv.Glob('*.cc'),
        myenv.Glob('arch/$ARCH/*.cc'),
        myenv.Glob('arch/$ARCHTYPE/*.cc') if myenv['ARCHTYPE'] != myenv['ARCH'] else [],
        myenv.Glob('arch/$ARCH/*/*.cc')
    ],
    libs = ['X11', 'rt'] if myenv['ARCH'] == 'host' else []
)
