Import('env')
myenv = env.Clone()
myenv['CXXFLAGS'] = str(myenv['CXXFLAGS']).replace('-flto', '')
lib = myenv.StaticLibrary(
    target = 'libheap',
    source = myenv.Glob('*.cc'),
)
myenv.Install(myenv['LIBDIR'], lib)
