Import('env', 'hostenv')

myenv = hostenv.Clone()
myenv.Append(
    CPPFLAGS = ' -D__LINUX__',
    CPPPATH = ['.', '../common']
)

prog = myenv.Program(
    target = 'linux-replay',
    source = [
        myenv.Glob('*.cc'), myenv.Glob('traces/*.c'),
        'common/buffer.cc', 'common/traceplayer.cc', 'common/traces.cc'
    ]
)
