// This file has been automatically generated by strace2c.
// Do not edit it!

#include "common/op_types.h"

trace_op_t trace_ops[] = {
    /* #1 */ { .opcode = OPEN_OP, .args.open = { 3, "SConstruct", O_RDWR, 0 } },
    /* #2 */ { .opcode = OPEN_OP, .args.open = { 4, "b", O_RDWR, 0 } },
    /* #3 */ { .opcode = LSEEK_OP, .args.lseek = { 0, 3, 0, SEEK_SET } },
    /* #4 */ { .opcode = READ_OP, .args.read = { 1024, 3, 1024, 2 } },
    /* #5 */ { .opcode = LSEEK_OP, .args.lseek = { 0, 4, 0, SEEK_SET } },
    /* #6 */ { .opcode = READ_OP, .args.read = { 1024, 4, 1024, 2 } },
    /* #7 */ { .opcode = CLOSE_OP, .args.close = { 0, 3 } },
    /* #8 */ { .opcode = CLOSE_OP, .args.close = { 0, 4 } },
    { .opcode = INVALID_OP }
};
