Import('env')

archtype = 'th' if env['ARCH'] == 't2' or env['ARCH'] == 't3' else 'host'
lib = env.StaticLibrary(
    target = 'libc',
    source = [
        env.Glob('*/*.cc'),
        env.Glob('arch/' + archtype + '/*.cc'), env.Glob('arch/' + archtype + '-$MACH/*.cc'),
        env.Glob('arch/$ARCH/*.cc'), env.Glob('arch/$ARCH-$MACH/*.cc')
    ]
)
env.Install(env['LIBDIR'], lib)
