import os

Import('env')
env.InstallFiles('$FSDIR/bench', '.', scan=1)
env.M3Strip('$FSDIR/bench/bin/noop', '$BINARYDIR/noop')

bpe = 0 if os.environ.get('M3_FSBPE') is None else int(os.environ.get('M3_FSBPE'))
blocks = 16384 if os.environ.get('M3_FSBLKS') is None else int(os.environ.get('M3_FSBLKS'))
env.M3Mkfs(target = 'bench.img', source = '$FSDIR/bench', blocks = blocks, inodes = 256, blks_per_ext = bpe)

args = '--sim' if env['MACH'] == 'sim' else ''
env.M3FileDump(target = 'bench.img.mem', source = 'bench.img', addr = 0x1000000, args = args)
