import os

Import('env')
env.InstallFiles('$FSDIR/bench', '.', scan=1)

for f in env.Glob('$BINARYDIR/*'):
    if not f.abspath.endswith('kernel') and not f.abspath.endswith('.a'):
        env.M3Strip('$FSDIR/bench/bin/${SOURCE.file}', f)

bpe = 0 if os.environ.get('M3_FSBPE') is None else int(os.environ.get('M3_FSBPE'))
if os.environ.get('M3_FSBLKS') is None:
    if env['ARCH'] == 't2' or env['ARCH'] == 't3':
        blocks = 65536
    else:
        blocks = 16384
else:
    blocks = int(os.environ.get('M3_FSBLKS'))
env.M3Mkfs(target = 'bench.img', source = '$FSDIR/bench', blocks = blocks, inodes = 2048, blks_per_ext = bpe)

if env['ARCH'] == 't2' or env['ARCH'] == 't3':
    args = '--sim' if env['ARCH'] == 't3' else ''
    env.M3FileDump(target = 'bench.img.mem', source = 'bench.img', addr = 0x1000000, args = args)
