// This file has been automatically generated by strace2c.
// Do not edit it!

#include "common/op_types.h"

trace_op_t trace_ops[] = {
    /* #1 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 19915 } },
    /* #2 */ { .opcode = OPEN_OP, .args.open = { 3, "/tmp/test", O_WRONLY|O_CREAT|O_TRUNC, 037777770001 } },
    /* #3 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 1651 } },
    /* #4 */ { .opcode = WRITE_OP, .args.write = { 4096, 3, 4096, 4 } },
    /* #5 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 1399 } },
    /* #6 */ { .opcode = CLOSE_OP, .args.close = { 0, 3 } },
    /* #7 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 45802 } },
    { .opcode = INVALID_OP } 
};
