import os

Import('env', 'hostenv')

dirs = ['strace2cpp', 'm3fs']
if env['ISA'] == os.popen("uname -m").read().strip():
    dirs += ['linux']

for d in dirs:
    hostenv.SConscript(d + '/SConscript', exports = ['env', 'hostenv'])
