Import('env')

myenv = env.Clone()
myenv.Append(LINKFLAGS = ' -Wl,--section-start=.text=0x1000')
myenv.M3Program(
    myenv,
    target = 'idle',
    source = [myenv.Glob('*.S'), myenv.Glob('*.cc')],
    NoSup = True,
    varAddr = False
)
