Import('env')

myenv = env.Clone()
myenv.Append(LINKFLAGS = ' -Wl,--section-start=.text=0x3FFF00')
myenv.M3Program(
    myenv,
    target = 'idle',
    source = [myenv.Glob('*.S')],
    NoSup = True,
    varAddr = False
)
