import os

Import('env')

sources = [
    env.Glob('*.cc'), env.Glob('*/*.cc'),
    env.Glob('arch/$ARCHTYPE/*.S'), env.Glob('arch/$ARCHTYPE/*.cc'),
    env.Glob('arch/$ARCH/*.S'), env.Glob('arch/$ARCH/*.cc')
]
if env['ARCH'] != 'host':
    sources += [env.Glob('arch/baremetal/*.cc')]

lib = env.StaticLibrary(
    target = 'libbase',
    source = sources
)
env.Install(env['LIBDIR'], lib)
